//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class autoservice1Entities : DbContext
    {
        public autoservice1Entities()
            : base("name=autoservice1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<car> car { get; set; }
        public virtual DbSet<client> client { get; set; }
        public virtual DbSet<detail> detail { get; set; }
        public virtual DbSet<detail_list> detail_list { get; set; }
        public virtual DbSet<employment> employment { get; set; }
        public virtual DbSet<executor> executor { get; set; }
        public virtual DbSet<protocol> protocol { get; set; }
        public virtual DbSet<work> work { get; set; }
    }
}
